#!/usr/bin/env node
/**
 * 產生部署用的 3 組 secret（cross-platform）
 *
 * 取代 generate-secrets.sh — 不依賴 openssl，純 Node.js crypto。
 *
 * 用法：
 *   node scripts/deploy/generate-secrets.mjs
 *
 * 輸出：直接打印到 stdout，可 redirect 到 .env.production：
 *   node scripts/deploy/generate-secrets.mjs >> .env.production
 */
import { randomBytes } from "node:crypto";

function hex32() {
  return randomBytes(32).toString("hex"); // 64 char hex = 32 bytes
}

console.log(`# Auto-generated by scripts/deploy/generate-secrets.mjs at ${new Date().toISOString()}`);
console.log(`# 重要：產出後務必備份這三組金鑰`);
console.log(`#   - SESSION_SECRET 變動 → 所有登入 session 失效（使用者要重登）`);
console.log(`#   - INTERNAL_SECRET 變動 → 重設 app/bridge 對應、雙邊都要更新`);
console.log(`#   - TELEGRAM_SESSION_KEY 變動 → 所有 TG 帳號需重新綁定，無法救`);
console.log(`#`);
console.log(`SESSION_SECRET=${hex32()}`);
console.log(`INTERNAL_SECRET=${hex32()}`);
console.log(`TELEGRAM_SESSION_KEY=${hex32()}`);
